USE [master]
GO

/****** Object:  Database [ProjekatAsp]    Script Date: 11.6.2023. 00:05:59 ******/
CREATE DATABASE [ProjekatAsp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjekatAsp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ProjekatAsp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProjekatAsp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ProjekatAsp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjekatAsp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjekatAsp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjekatAsp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjekatAsp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjekatAsp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjekatAsp] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjekatAsp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProjekatAsp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjekatAsp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjekatAsp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjekatAsp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjekatAsp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjekatAsp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjekatAsp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjekatAsp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjekatAsp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProjekatAsp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjekatAsp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjekatAsp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjekatAsp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjekatAsp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjekatAsp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProjekatAsp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjekatAsp] SET RECOVERY FULL 
GO

ALTER DATABASE [ProjekatAsp] SET  MULTI_USER 
GO

ALTER DATABASE [ProjekatAsp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjekatAsp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjekatAsp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjekatAsp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProjekatAsp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProjekatAsp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ProjekatAsp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProjekatAsp] SET  READ_WRITE 
GO

